# Makefile lunedi_angelo #

lunedi_angelo: lunedi_angelo.c Makefile
	gcc -ansi -Wall -O lunedi_angelo.c -o lunedi_angelo

pulisci:
	rm -f lunedi_angelo.o

pulisci_tutto:
	rm -f lunedi_angelo lunedi_angelo.o
