blank_issues_enabled: true
contact_links:
  - name: Discussioni
    url: https://github.com/itsPinguiz/InformaticaUniurb/discussions
    about: Usa le discussioni per domande generali sul repository o sui corsi.
