unione_e_differenza_linguaggi: unione_e_differenza_linguaggi.c makefile
	gcc -ansi -Wall -O unione_e_differenza_linguaggi.c -o unione_e_differenza_linguaggi
pulisci:
	rm -f unione_e_differenza_linguaggi.o
pulisci_tutto:
	rm -f unione_e_differenza_linguaggi unione_e_differenza_linguaggi.o
